### PR TITLE
Pipeline reducer implementation

### PR DESCRIPTION
**Pull request by pshevtsov**
This PR introduces the Pipeline reducer which applies other reducers one by one using the output of the previous reducer as the input for the next one.

### CODE REVIEW

**Comment by satyrius** [comment]
What's the difference with `Chain` reducer that library already has?

**Comment by pshevtsov** [comment]
`Chain` reducer applies other reducers onto the initial input, while `Pipeline` reducer uses the output of the previous reducer as the input for the next one.

**Comment by pshevtsov** [comment]
For example, the final result of [this `Reduce` call](https://github.com/pshevtsov/gonx/blob/pipeline_reducer/reducer_test.go#L235-L239) is the following:

>```
&{map[count:2.00]}
```

(the average of the `count` field — float)

While using the same reducers for `Chain` reducer results with

>```
&{map[count:2]}
```

(integer!)

It ain't calculates average since there's no field `count` in the initial input entries fields.

**Comment by pshevtsov** [comment]
I was targeting to use this reducer along with `Interval` reducer introduced in #11:

1. Filter entries by timestamp interval
1. Apply other reducers onto the filtered entries

For example, count all (log) entries for the previous day.

**Comment by satyrius** [comment]
The `Filter` interface was introduced in https://github.com/satyrius/gonx/pull/19, so you could apply filter and reduce limited input. So we don't need `Pipeline` as a new reducer, `Chain` do this job. But still thanks for feature request, it inspire me to implement `Filter` interface!
